# Generated by Django 2.0.6 on 2018-06-17 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Company',
            new_name='Promotions',
        ),
    ]
