# Generated by Django 2.0.6 on 2018-06-08 23:07

from django.db import migrations, models
import kinds_companies.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kind_Company',
            fields=[
                ('id_kind', models.CharField(default=kinds_companies.models.create_id, editable=False, max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('subtitle', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=200)),
            ],
        ),
    ]
