# Generated by Django 2.0.6 on 2018-06-11 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='deviceId',
            new_name='device_id',
        ),
    ]
