# Generated by Django 2.0.6 on 2018-06-11 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20180611_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='device_id',
        ),
        migrations.AlterField(
            model_name='client',
            name='id_client',
            field=models.CharField(editable=False, max_length=200, primary_key=True, serialize=False),
        ),
    ]
