# Generated by Django 2.0.6 on 2018-06-11 16:19

from django.db import migrations, models
import reports.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id_report', models.CharField(default=reports.models.create_id, editable=False, max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('lat', models.CharField(max_length=200)),
                ('lon', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('likes', models.IntegerField()),
                ('dislikes', models.IntegerField()),
                ('repair', models.IntegerField()),
            ],
        ),
    ]
