# Generated by Django 2.0.6 on 2018-06-11 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_reports_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='date',
            field=models.CharField(default='hoy', max_length=200),
            preserve_default=False,
        ),
    ]
