# Generated by Django 2.0.6 on 2018-06-08 22:03

import companies.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campana',
            fields=[
                ('id_company', models.CharField(default=companies.models.create_id, editable=False, max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('street', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=200)),
                ('lat', models.CharField(max_length=200, null=True)),
                ('lon', models.CharField(max_length=200, null=True)),
                ('service_hour', models.CharField(max_length=200, null=True)),
                ('type_company', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
