# Generated by Django 2.0.6 on 2018-06-08 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Campana',
            new_name='Company',
        ),
    ]
