# Generated by Django 2.0.6 on 2018-06-08 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kinds_companies','0001_initial')
        ('companies', '0002_auto_20180608_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='type_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kinds_companies.Kind_Company'),
        ),
    ]
